Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: mysql
    SupplierDeployMetadata:
      UserType: Aliyun
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 'templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 该套餐采用了2vCPU 4GB内存的ECS实例（ecs.c6.large），并且绑定了SLB（slb.s1.small），满足基本的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.large']
                SlbInstanceType: slb.s1.small
              Type: Noraml
              OrderList:
                - EcsInstanceType
                - SlbInstanceType
            - Name: 基础版
              Description: 该套餐采用了4vCPU 8GB内存的ECS实例（ecs.c6.xlarge），并且绑定了SLB（slb.s1.small），该配置可以满足大部分的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.xlarge']
                SlbInstanceType: slb.s1.small
              Type: Noraml
              OrderList:
                - EcsInstanceType
                - SlbInstanceType
            - Name: 高配版
              Description: 该套餐采用了8vCPU 16GB内存的ECS实例（ecs.c6.2xlarge），并且绑定了SLB（slb.s3.small），该配置使用了更高规格ECS和SLB，进一步提升了架构的稳定性和性能。
              Parameters:
                EcsInstanceType: ['ecs.c6.2xlarge']
                SlbInstanceType: slb.s3.small
              Type: Noraml
              OrderList:
                - EcsInstanceType
                - SlbInstanceType
          HiddenParameterKeys:
            - EcsInstanceType
            - SlbInstanceType
            - VpcId
            - VSwitchId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: ${VpcId}
                  ParameterMappings:
                    - ParameterKey: ZoneId
                      ParameterMappingKeys:
                        - VSwitchId
                      ParameterValueMapping:
                        ${ZoneId}:
                          Parameters:
                            VSwitchId: ${VSwitchId}
      FileArtifactRelation:
        '{{ computenest::file::MySQL }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: templates/parameters.yaml
        AllowedRegions:
          - cn-hangzhou
        PredefinedParameters:
        - Name: 低配版
          Parameters: {}
          Description: 该套餐采用了2vCPU 4GB内存的ECS实例（ecs.c6.large），并且绑定了SLB（slb.s1.small），满足基本的业务需求。
          Type: Noraml
          OrderList:
            - EcsInstanceType
            - SlbInstanceType
        - Name: 基础版
          Parameters: {}
          Description: 该套餐采用了4vCPU 8GB内存的ECS实例（ecs.c6.xlarge），并且绑定了SLB（slb.s1.small），该配置可以满足大部分的业务需求。
          Type: Noraml
          OrderList:
            - EcsInstanceType
            - SlbInstanceType
        - Name: 高配版
          Parameters: {}
          Description: 该套餐采用了8vCPU 16GB内存的ECS实例（ecs.c6.2xlarge），并且绑定了SLB（slb.s3.small），该配置使用了更高规格ECS和SLB，进一步提升了架构的稳定性和性能。
          Type: Noraml
          OrderList:
            - EcsInstanceType
            - SlbInstanceType
    NetworkMetadata:
      EnablePrivateVpcConnection: true
      EnableReversePrivateVpcConnection: false
      PrivateVpcConnectionMode: PrivateLink
      PrivateVpcConnectionType: DynamicTemplate
      PrivateVpcConnections:
        - Name: default
          PrivateZoneName: ${ServiceInstanceId}.computenest.aliyuncs.com
          NetworkDynamicTemplateSource: TEMPLATE_RESOURCE
          NetworkDynamicTemplateResourceType: SLB
          DynamicTemplateParameterKey: Slb
          Payer: Endpoint
  ServiceType: managed
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: 单机版
        Operation:
          - Name: 网络变配
            Description: 网络变配支持VPC私网变更和自定义域名变更
            Type: Custom
            EnablePrivateVpcConnection: true
            EnablePrivateZoneName: true
          - Name: 磁盘容量扩容
            Description: 扩容磁盘容量
            Type: Upgrade
            Parameters:
              - DataDiskSize
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: mysql demo
    Image: 'icons/service_logo.jpg'
    Name: MySQL托管版beta1
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: MySQL
    Description: MySQL
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'artifacts/mysql-community-release-el6-5.noarch.rpm'